import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import { api } from "~/utils/api";
import { useState } from "react";

const CreatePost: NextPage = () => {
  const [prompt, setPrompt] = useState("");
  const [content, setContent] = useState("");
  const response = api.openAi.generateCompletion.useMutation({
    
    onSuccess: (data) => {
      if (!data.response) return;
      setContent(data.response);
      console.log(data);
    },
  });

  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    response.mutate({ text: prompt });
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-2xl tracking-tight text-white">Create post</h1>
          <div>
            <form onSubmit={handleSubmit} className="flex flex-col">
              <input
                className="my-2"
                autoFocus
                onChange={(e) => setPrompt(e.target.value)}
                placeholder="Title"
                type="text"
                value={prompt}
              />
              <textarea
                cols={50}
                onChange={(e) => setContent(e.target.value)}
                placeholder="Content"
                rows={8}
                value={content}
              />
              <input
                className="my-2 cursor-pointer bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
                disabled={!prompt}
                type="submit"
                value="Create"
              />
              {/* <Link className="back" href="#" onClick={() => router.push("/")}>
                    or Cancel
                  </Link> */}
            </form>
          </div>
        </div>
      </main>
    </>
  );
};

export default CreatePost;
