import { type NextPage } from "next";
import Head from "next/head";
import GenerateImg from "~/components/GenerateImg";

const CreateImage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create post</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-full flex-col items-center justify-center mx-5">

          <GenerateImg />

      </main>
    </>
  );
};

export default CreateImage;
